# ===== Application =====
spring.application.name=student-management
server.port=8080

# ===== DataSource: SQL Server =====
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HSF302_CH6;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Map mọi String -> NVARCHAR để lưu được tiếng Việt
spring.jpa.properties.hibernate.use_nationalized_character_data=true
# Tắt Open Session In View: mọi truy cập DB phải xong trong Service
spring.jpa.open-in-view=false

# ===== Thymeleaf =====
spring.thymeleaf.cache=false

# ===== Logging =====
logging.level.com.hsf302=DEBUG
